sudo: required
language: java
services:
  - docker
install: true
script:
  - docker build --tag=sdkman/sdkman-cli .
  - docker run --rm -v $PWD:/usr/src/app -v $HOME/.gradle:/root/.gradle sdkman/sdkman-cli clean test --info
deploy: 
    provider: script
    script: bin/deploy.sh
    on:
        tags: true
        branch: master
before_cache:
  - sudo rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
